### PR TITLE
Bump to our saml2 fork, add onelogin tests

### PR DESCRIPTION
**Pull request by brettkiefer**
Add the OneLogin examples from
https://developers.onelogin.com/saml/examples/response

At saml2 1.8.1, only onelogin/3_saml_response_with_signed_message.xml
passes. With our fork,
onelogin/4_saml_response_with_signed_message_and_assertion.xml also
passes, and that appears to be analogous to the IBM case.

### CODE REVIEW

**Comment by mgduk** [comment]
@brettkiefer do you have access to any examples to test the negative case — where the signing _shouldn't_ be accepted?

**Comment by mgduk** [comment]
Also, can you commit the updated shrinkwrap file, with whichever bits you've updated — `saml2-js` at a minimum I guess.

**Comment by brettkiefer** [comment]
No, no negative examples, but it shouldn't be hard to compose some by just maiming the signatures or including other XML -- but I'd expect us to contribute those to the saml2-js lib.

**Comment by brettkiefer** [comment]
Oh that's my bad, I didn't see the shrinkwrap file there. Updated, amended, force-pushed.

**Comment by brettkiefer** [comment]
On this repo, you can 'Merge pull request' once you're happy with it.

**Pull request merged**
